name: verus

on: [push, pull_request, workflow_dispatch]

jobs:
  verus:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get Verus release info
        id: verus-release-info
        #uses: pozetroninc/github-action-get-latest-release@v0.8.0
        uses: ./.github/actions/latest-github-release
        with:
          repository: verus-lang/verus
          excludes: "draft"
      - name: acquire verus
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf ${{ steps.verus-release-info.outputs.url }} | unzip -
      - name: run Verus
        working-directory: ./tasks
        run: |
          # Run `verus` on each file, collecting failures if any
          ANYFAILED=""
          for i in *.rs; do
            echo -n "[verus] $i: "
            if verus "$i" >/dev/null 2>/dev/null; then
              echo "success"
            else 
              echo "failed"
              # Re-run `verus` on any failure just to display the actual output
              verus "$i" || true
              ANYFAILED="$ANYFAILED $i"
            fi
          done
          if [ -n "$ANYFAILED" ]; then
            echo "Failed:$ANYFAILED"
            exit 1
          fi
